GRD-617
oicr-gsi/bcl2barcode pull request #4
Opened 2023-07-06 19:15 UTC by hannahdriver

Updating README to include commands.

2023-07-06 20:17 UTC, bibilujan commented
@hannahdriver can you add a CHANGELOG 
Unreleased #date
#your changes

## 1.0.2 - 2021-05-28
- migrate to Vidarr

2023-07-06 21:03 UTC, hannahdriver commented
> @hannahdriver can you add a CHANGELOG Unreleased #date #your changes
> 
> ## 1.0.2 - 2021-05-28
> * migrate to Vidarr

Yes, done!

2023-07-07 01:35 UTC, pruzanov requested changes
Also, I believe it would be better if you consider prettifying the command section - making it more readable, see delly for an example

2023-07-07 01:35 UTC, pruzanov commented on README.md
>  ## Niassa + Cromwell
THis section is not needed since we are not using Niassa anymore. It is a relic from the past

2023-07-07 13:36 UTC, hannahdriver commented on README.md
>  ## Niassa + Cromwell
Deleted, thanks!

Sorry, I'm not sure I understand what you mean by prettifying the command section. I noticed in the delly README, the headers for each command aren't bolded - would you like me to change the headings to normal text for this one?

2023-07-07 16:16 UTC, hannahdriver commented on README.md
>  ## Niassa + Cromwell
Deleted, thanks!

I have updated the commands section for readability - let me know if it looks okay!

2023-07-07 17:01 UTC, bibilujan approved these changes

2023-07-07 17:01 UTC, bibilujan commented on README.md
>  ## Niassa + Cromwell
Can you remove this section of the README, its not needed anymore as Niassa no longer exists.

2023-07-08 02:14 UTC, pruzanov approved these changes

2023-07-08 02:16 UTC, pruzanov commented
I approved, but it looks like the build is failing. It may be transient, need to check what Jenkins says

2023-07-13 23:18 UTC, merged